Don't delete files from 2.16.0 onwards.
They are fixed, and removing them can cause NoClassDefFoundError at
runtime.

Also, synchronise access to the JAR file we are modifying, just in case
Gradle resolves two configurations concurrently which both resolve to
include the same JAR.  (We could have a separate lock per JAR file path
for performance but that seems excessive.)